---
title: "Report"
output: 
  html_document:
    code_folding: hide
    always_allow_html: true
    css: style.css
---

# Motivation 

The cookies anecdote is fun but the school bus delay is a serious issue. The council of the city of New York states that every year starts with a higher rate of delays caused by major traffic because the department of education has not equipped bus companies or drivers with information early enough for drivers to familiarize themselves with their route and map out their timing. Also, it is unconscionable that year after year, the Department of Education's insufficient planning is exacerbating the stress felt by families starting a new school year. We were interested in exploring factors that cause school bus delay and understand the major reason behind bus delay. Distribution of bus delay is also what we want to figure out. 



# Related Work
According to an analysis by [Chalkbeat in partnership with the CITY](https://ny.chalkbeat.org/2021/9/13/22672760/school-buses-leave-nyc-students-stranded-on-first-day), busing complaints have grown in recent years. In 2019, there were an average of 500 delays a day druing the first weeks of school, which was up 5% from a year before.We realized that school bus delay is a serious issue after reading their work.


# Data

Data
The bus delay data in New York were obtained from [NYC open data](https://data.cityofnewyork.us/Transportation/Bus-Breakdown-and-Delays/ez4e-fazm). The data set contains huge amount of data (more than 500,000 observations). Due to the time limit and computer processing power, data from January 1, 2018 to September 30, 2021 were selected. These data contained information about where delay happened, delay time, school name and so on.

The geolocation information of school were obtained from opt1 [data.world](https://data.world/city-of-ny/8wau-idzf/workspace/file?filename=prek-vendors-by-transportation-site-1.csv), opt2 [data.world](https://data.world/city-of-ny/hg3c-2jsy/workspace/file?filename=transportation-sites-1.csv). We join these two opt data sets and school bus delays data to get the location and delays information of schools in New York.


# Data Analysis





# Data Explortary

To have some statistical understanding of our data, we decided to take a step further before moving on to modeling.

While looking at the reason of school bus delays, we see that heavy traffic is the main reason and all other reasons plays a minor part. This lead us to ask the question, whether the distribution of school bus delay reasons is the same across 2018-2021 school years.Though we include data in 2021-2022 Fall, yet the counts isn't comparable with other school years. So we only look at the 3 school years including, 2018-2019, 2019-2020, 2020-2021.To answer our question, we conducted a chi-square test. From the test result,we conclude that the reasons of delay have a different distribution across the school years though they seem about the same in our bar plots. Our guess is that although the leading reason remains to be heavy traffic, the percentage of heavy traffic being the reason is actually decreasing over the years.Given that the distribution of delay reasons varies from year to year, we decide to look at the nearest pre-pandemic school year. The reason we focus on 2019-2020 school year is that we assume the post pandemic situation should be similar with the nearest pre pandemic situation. 

Looking at the plot in the distribution of delay reasons,we believe that the frequency of different reasons should not be the same. And now we want to verify our assumption using a chi-square test.From the result, we have enough evidence to say that the frequency of delay reasons are not equally distributed in 2019-2020 school year.

we also noticed that the delay counts varies among each month. We can see from the yearly distribution plot of school bus delays we see that winter time tend to have more delays, thus, we propose hypothesis that there is no homogeneity in delay counts in each months. According to the chi-square test result we conclude that there's no difference of delay counts between months. The counter-intuitive result may be caused by the lock down during April to May of 2020.We don't have any information on these 2 month therefore we are only testing the "winter month".

We know there's no difference of delay counts between months in 2019-2020. But what about different weekdays? I remembered that I was always late for school on Monday. Is it my personal problem? Maybe because of more school bus delays on Monday? To find out the real reason,we use Chi-squared test to see whether there is  homogeneity in delay counts for each weekday. According to the chi-square test result we conclude that there's no statistically difference among weekdays at 0.05 significant level. Unfortunately, there is homogeneity in the delay counts for each weekday. It seems that the reason I was always late on Monday was I still missed my weekend.

# Reason Part


The goal of the contributing factor analyses is to understand the major reasons that lead to the bus delay in Manhattan across three consecutive school years (2018-2019,2019-2020, and 2020-2021). We hypothesized that the heavy traffic and weather conditions may result in the most delay. We first compared the top contributing factors of bus delay in each year. From the bar graph, it is not difficult to find that heavy traffic is the most important reason resulting in bus delay and it is considered as the common factor with high frequency. The top three reasons for bus delay are heavy traffic, a mechanical problem and others. In the stacked bar graph, it is interesting to see that the number of delays per year is decreasing. We suspect that the potential reason for the reduction in delays is due to the COVID-19 and the quarantine policy associated with COVID. Because the difference of frequency between factors is quite large, we decide to show the proportion of each reason based on total delay within three years. Based on the pie chart, we notice that roughly 90% of bus delay is due to heavy traffic and 5.35 % of delay is due to a mechanical problem, and approximately 4% of delay is due to others. This result is roughly the same across three years.

Furthermore, we want to examine the possible relationship between heavy traffic and rainfall as well as between heavy traffic and snow depth. We combine our data with the NOAA dataset from the P8105 website and extract the precipitation and snow depth value from the dataset. We exclude the cases when there is no snow depth and rainfall in the graph we design. According to the scatter plot, more traffic occurred when rainfall is roughly below 100mm, which will be either light rain or moderate rain. We did not see any association between heavy rain and the amount of precipitation. The year 2020-2021 have less rainfall and fewer cases of bus delay compared to other years. We also study the association between heavy traffic and snow depth. Due to the lack of variability of snow depth in 2019-2020, we are unable to do the comparison across years. However, there is a negative association between snow depth and delays because of heavy traffic in 2018-2019; and no association between snow depth and delay is shown in 2020-2021. Since the weather differs from year and year and the data we obtain is not sufficient enough, we can further investigate the issue with a larger dataset.

Finally, we examine the relationship between weekdays and heavy traffic. We calculate the average delay due to heavy traffic per weekday across three years. We observe that heavy traffic happens frequently on Thursday and less frequently on Monday. In the school year 2020-2021, it is almost equally likely to have a similar number of delays on school days. 


# Mapping Part

We considered the geolocation of schools in New York city from 2015 to 2019. Compared with other areas, schools in Manhattan have more delays in school buses, and the time of delays are longer. Therefore our project is mainly for schools in Manhattan. Data in these geolocation and density heatmap plots helped identify certain neighborhoods in Manhattan that appear to have more and longer delays  and they include East Harlem and Lower East Side, as well as the Hudson Yards.

#Contributors: Qingdou Han, Guiyi Cai, Xiangqi Chen, Huili Zheng and Hanfu Shi

