---
title: "Trend of School Bus Delay Over Time"
subtitle: "Bike use and bike and microvehicles crashes over time"
date: 
output: 
  html_document:
    code_folding: hide
    always_allow_html: true
---

```{r setup, include=FALSE}
library(tidyverse)


knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "right"))
```

# Daily Delay Counts : from 9/15/2018 - 11/18/2021

```{r}
#read data in
df = read_csv("data/clean_data.csv")

#plot data: drop NA rows
plot_df = df %>% 
  select(school_year, year, how_long_delayed,occur_date, day, month,busbreakdown_id) %>% 
  na.omit()

#plot daily delay counts

plot_df %>% 
  group_by(occur_date) %>% 
  summarise(delay_count = n(),school_year) %>% 
  ggplot(aes(x = occur_date, y = delay_count)) +
  geom_point(alpha = .3) +
  geom_smooth(se = FALSE) +
  facet_grid(~school_year,scales = "free") + 
  labs(
    title = "Daily School Bus Delay Counts in Manhattan",
    x = "Date",
    y = "Counts"
  ) +
  theme(axis.text.x = element_text(angle = 60, vjust = 0.5, hjust = 1))
  


```


Lets Look at The Distribution of Delay Times in Each School Year

```{r}

delay_time_dist = 
  plot_df %>% 
  ggplot(aes(x = how_long_delayed,fill = how_long_delayed))+
    geom_bar(position = "dodge")+
  facet_grid(~school_year,scales = "free") + 
  labs(
    title = "Distribution of School Bus Delay Time in Manhattan",
    x = "Delay Time",
    y = "Counts"
  )+
  theme(axis.title.x = element_blank(),axis.text.x = element_text(angle = 60, vjust = 0.5, hjust = 0.5)) + 
  guides(fill=guide_legend(title="Delay Time"))

ggplotly(delay_time_dist)
```

lets now overlap the school bus delay counts within each school year 

```{r}
#overlaping each year's daily delay counts
plot_df %>% 
 group_by(occur_date) %>% 
  mutate(delay_count = n(),
         day_of_month = lubridate::mday(occur_date),
         common_day = lubridate::mdy(paste(month, day_of_month,"2021")))%>%
  ggplot(aes(x = common_day, y = delay_count, group = school_year, color = school_year)) +
  geom_point(alpha = .3) +
  geom_smooth(se = FALSE) + 
  labs(
    title = "School Bus Delay in Manhattan",
    x = "Month",
    y = "Delay Counts"
    ) +
  scale_x_date(date_breaks = "1 month", labels = function(x) format(x, "%b")) 
```

